CREATE TABLE [dbo].[Product]
(
	[Id] INT NOT NULL PRIMARY KEY IDENTITY,
	[ProductName] NVARCHAR(100) NOT NULL,
	[Description] NVARCHAR(550),
	[RetailPrice] MONEY NOT NULL,
	[QuantityInStock] INT NOT NULL DEFAULT 1,
	[CreateDate] DATETIME2 DEFAULT GETUTCDATE() NOT NULL,
	[LastModified] DATETIME2 DEFAULT GETUTCDATE() NOT NULL, 
    [IsTaxable] BIT DEFAULT 1 NOT NULL
)
